// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BrewingController_2 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager;
		
		protected System.Web.UI.Timer UpdateTemp;
		
		protected System.Web.UI.UpdatePanel TempPanel1;
		
		protected System.Web.UI.WebControls.Label TempLabel1;
		
		protected System.Web.UI.WebControls.Label CurrentSetTemp1;
		
		protected System.Web.UI.WebControls.TextBox TempSet1;
		
		protected System.Web.UI.WebControls.Button SendTemp1;
		
		protected System.Web.UI.UpdatePanel TempIndicator1;
		
		protected System.Web.UI.WebControls.Label HeatingIndicator1;
		
		protected System.Web.UI.UpdatePanel TempPanel2;
		
		protected System.Web.UI.WebControls.Label TempLabel2;
		
		protected System.Web.UI.UpdatePanel TempPanel3;
		
		protected System.Web.UI.WebControls.Label TempLabel3;
		
		protected System.Web.UI.WebControls.Label CurrentSetTemp3;
		
		protected System.Web.UI.WebControls.TextBox TempSet3;
		
		protected System.Web.UI.WebControls.Button SendTemp3;
		
		protected System.Web.UI.UpdatePanel TempIndicator3;
		
		protected System.Web.UI.WebControls.Label HeatingIndicator3;
		
		protected System.Web.UI.WebControls.Button PumpButton1;
		
		protected System.Web.UI.WebControls.Label Pump1Status;
		
		protected System.Web.UI.WebControls.Button PumpButton2;
		
		protected System.Web.UI.WebControls.Label Pump2Status;
		
		protected System.Web.UI.WebControls.Button AllPumpsOff;
	}
}
