// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BrewingController {
	
	
	public partial class Home {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList1;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList2;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList3;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.Button StartSessionButton;
	}
}
